export const ErrorMessage = {
  ERR_INVALID_REQUEST: 'ERR_INVALID_REQUEST',
  ERR_NO_REQUEST_DATA: 'ERR_NO_REQUEST_DATA',
  ERR_DRIVER_HAS_NO_CONTEXT: 'ERR_DRIVER_HAS_NO_CONTEXT',
  ERR_CANNOT_PARSE_DRIVER_CONFIG: 'ERR_CANNOT_PARSE_DRIVER_CONFIG',
}
